### ISSUE TITLE
Dead page if there is no slides

### ISSUE THREAD

**Issue by DenisNeustroev** [jhpratt/skrolr#11]

**Comment by jhpratt** [comment]
I think the issue is that you're trying to create a slider without slides, which make no sense as to why you'd want to do that. If you're just trying to get a feel for the placement of things, it'd be much easier to create an empty block element and replace it later.

At least for now, I can't see myself creating a solution to this, as doing this defeats the use case of the library.

**Comment by DenisNeustroev** [comment]
I agree, but it was difficult to debug. It may be necessary to document this behavior?

**Comment by jhpratt** [comment]
I'll add it in the wiki, but I can't think of any reason you'd want to use this without slides. What were you trying to achieve?

**Comment by DenisNeustroev** [comment]
It's just a blank state when someone create a new page with a slider inside, but don't yet fill slider itself.

**Comment by jhpratt** [comment]
Yes, I understand that. Why would you want to do that, though?

**Comment by DenisNeustroev** [comment]
It's just a case in my app: someone adds a product, but do not yet load images for it, so I get a blank state between adding a product and uploading images for slider, but it's not a problem, I have fixed it.

**Comment by jhpratt** [comment]
Ah, ok. If you modified *skrolr*'s code, would you mind sending a pull request?

**Comment by DenisNeustroev** [comment]
There aren't any modifications. I just do not run slider if there are not enough slides.

**Comment by jhpratt** [comment]
That's what I figured, but wasn't sure. Good luck getting your product up and running!
